### ISSUE TITLE
Not working with the New Issues Experience

### ISSUE THREAD

**Issue by swrobel** [N1ck/gifs-for-github#82]
With the [New Issues Experience](https://github.blog/changelog/2025-01-13-evolving-github-issues-public-preview/) experiment enabled:
<img width="966" alt="Image" src="https://github.com/user-attachments/assets/c862dc56-a818-425f-8f89-ad0a846346c9" />

The toolbar button is not showing up.

**Before enabling**
<img width="846" alt="Image" src="https://github.com/user-attachments/assets/f6cc343f-7261-4e08-b7bd-5941c716ff74" />

**After enabling**
<img width="873" alt="Image" src="https://github.com/user-attachments/assets/4b6cf80a-e2d5-479f-9d26-2692a5247c42" />

**Comment by N1ck** [comment]
<img src="https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExanFnM3prcDJxdGZnM3JwMTZic2g1azJxdms2b3kxcXZqbDYxNTgyeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3CYk12DauTifUJlIIL/giphy.gif" />


Thanks for raising @swrobel . I will try and take a look at fixing it this weekend!

**Comment by PatrykKuniczak** [comment]
@N1ck Let's take a look on PRs also 😆

**Comment by N1ck** [comment]
Still waiting for it to be approved in the Chrome Web Store, but this should hopefully be resolved in `v25.3.24`

**Comment by glepretre** [comment]
<img src="https://media0.giphy.com/media/v1.Y2lkPWJkM2VhNTdldXFwbWJqeWFhbXR6M3FnMHc4a3pnbWcwd2R5aXV6M2M1MDA1dHM5biZlcD12MV9naWZzX3NlYXJjaCZjdD1n/9kwOxInrc1eSdIFHUJ/giphy.gif"/>

**Comment by Eyal-Shalev** [comment]
I'm using version 25.10.13 and it is still not working in PRs

<img width="630" height="493" alt="Image" src="https://github.com/user-attachments/assets/3b9eae28-af31-451a-a060-e395b9d80b10" />
